.TH RNBD "8" "March 2020" "rnbd 1.0.3" "System Administration Utilities"
.SH NAME
rnbd - Configuration tool for RNBD driver and RTRS library.
.SH SYNOPSIS
rnbd client|server|help|version ...
.SH SYNOPSIS

    --help          Help output
    --verbose       Verbose output
    --debug         Debug mode
    --simulate      Only print modifying operations, do not execute
    --term          Assume terminal output


rnbd client|server|help|version ...

    client          Operations of client
    server          Operations of server
    help            Display help and exit
    version         Display version of this tool and exit


rnbd client devices|sessions|paths|help ...

    devices         Map/unmapped/modify devices
    sessions        Operate on sessions
    paths           Operate on paths
    help            Display help and exit


rnbd server devices|sessions|paths|help ...

    devices         Operate on devices
    sessions        Operate on sessions
    paths           Operate on paths
    help            Display help and exit


.SH DESCRIPTION
The commands of the tool are structured in the following fashion:
client vs server -> device vs. session vs. path. If the context of
a command is unambiguous, it can be also called directly.
For example: rnbd map (instead of rnbd client device map), rnbd session list
(instead of rnbd client session list), rnbd show client@server (instead of rnbd client session show client@server), etc.
.SH SUBCOMMANDS
.B

rnbd client device list [OPTIONS]

List information on devices.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session        Name of the RTRS session of the device
                    mapping_path    Mapping Path   Mapping name of the remote device
                    devname         Device         Device name under /dev/. I.e. rnbd0
                    devpath         Device path    Device path under /dev/. I.e. /dev/rnbd0
                    state           State          State of the RNBD device. (client only)
                    access_mode     Access Mode    RW mode of the device: ro, rw or migration
                    rx_sect         RX             Amount of data read from the device
                    tx_sect         TX             Amount of data written to the device
                    direction       Direction      Direction of data transfer: imported or exported

                    Default: sessname,mapping_path,devname,state,access_mode

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    notree          Don't display paths for each sessions
    noheaders       Don't print headers
    nototals        Don't print totals
    help            Display help and exit. [fields|all]


.B

rnbd client device show <device> [OPTIONS]

Show information about an rnbd block device.

Arguments:
    <device>        Name of a local or a remote block device.
                    I.e. rnbd0, /dev/rnbd0, d12aef94-4110-4321-9373-3be8494a557b.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session        Name of the RTRS session of the device
                    mapping_path    Mapping Path   Mapping name of the remote device
                    devname         Device         Device name under /dev/. I.e. rnbd0
                    devpath         Device path    Device path under /dev/. I.e. /dev/rnbd0
                    state           State          State of the RNBD device. (client only)
                    access_mode     Access Mode    RW mode of the device: ro, rw or migration
                    rx_sect         RX             Amount of data read from the device
                    tx_sect         TX             Amount of data written to the device
                    direction       Direction      Direction of data transfer: imported or exported

                    Default: sessname,mapping_path,devname,state,access_mode

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    help            Display help and exit. [fields|all]


.B

rnbd client device map <device> from <server> [OPTIONS]

Map a device from a given server

Arguments:
    <device>        Path to the device to be mapped on server side
    from <server>   Address, hostname or session name of the server

Options:
    <path>          Path(s) to establish: [src_addr@]dst_addr
                    Address is [ip:]<ipv4>, [ip:]<ipv6> or gid:<gid>
    {rw}            Access permission on server side: ro|rw|migration. Default: rw
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client device resize <device> <size> [OPTIONS]

Change size of a mapped device

Arguments:
    <device>        Name of the device to be resized
    <size>          New size of the device in bytes
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client device unmap <device> [OPTIONS]

Umap a given imported device

Arguments:
    <device>        Name of the device to be unmapped

Options:
    force           Force operation
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client device remap <device> [OPTIONS]

Unmap and map again an imported device

Arguments:
    <identifier>    Identifier of a device to be remapped.

Options:
    force           Force operation
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client session list [OPTIONS]

List information on sessions.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session name   Name of the session
                    path_cnt        Path cnt       Number of paths
                    act_path_cnt    Act path cnt   Number of active paths
                    state           State          State of the session.
                    path_uu         PS             Up (U) or down (_) state of every path
                    mp              MP Policy      Multipath policy
                    mp_short        MP             Multipath policy (short)
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    reconnects      Reconnects     Reconnects
                    direction       Direction      Direction of the session: incoming or outgoing
                    srvname         Server Name    Server name

                    Default: sessname,state,path_uu,mp_short,tx_bytes,rx_bytes,reconnects

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    notree          Don't display paths for each sessions
    noheaders       Don't print headers
    nototals        Don't print totals
    help            Display help and exit. [fields|all]


.B

rnbd client session show <session> [OPTIONS]

Show information about an rnbd session.

Arguments:
    <session>       Session name or remote hostname.
                    I.e. ps401a-1@st401b-2, st401b-2, <ip1>@<ip2>, etc.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session name   Name of the session
                    path_cnt        Path cnt       Number of paths
                    act_path_cnt    Act path cnt   Number of active paths
                    state           State          State of the session.
                    path_uu         PS             Up (U) or down (_) state of every path
                    mp              MP Policy      Multipath policy
                    mp_short        MP             Multipath policy (short)
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    reconnects      Reconnects     Reconnects
                    direction       Direction      Direction of the session: incoming or outgoing
                    srvname         Server Name    Server name

                    Default: sessname,state,path_uu,mp_short,tx_bytes,rx_bytes,reconnects

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    help            Display help and exit. [fields|all]


.B

rnbd client session remap <session> [OPTIONS]

Unmap and map again all devices of a given session

Arguments:
    <session>       Identifier of a session to remap all devices on.

Options:
    force           Force operation
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client session reconnect <session> [OPTIONS]

Disconnect and connect again a whole session

Arguments:
    <session>       Name or identifier of a session.

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client path list [OPTIONS]

List information on paths.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Sessname       Name of the session.
                    pathname        Path name      Path name
                    src_addr        Client Addr    Client address of the path
                    src_addr_s      Client Addr    Normalized client address.
                    dst_addr        Server Addr    Server address of the path
                    dst_addr_s      Server Addr    Normalized server address.
                    hca_name        HCA            HCA name
                    hca_port        Port           HCA port
                    state           State          Name of the path
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    reconnects      Reconnects     Reconnects
                    direction       Direction      Direction of the path: incoming or outgoing

                    Default: sessname,hca_name,hca_port,dst_addr_s,state,tx_bytes,rx_bytes,inflights,reconnects

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    notree          Don't display paths for each sessions
    noheaders       Don't print headers
    nototals        Don't print totals
    help            Display help and exit. [fields|all]


.B

rnbd client path show <path> [OPTIONS]

Show information about an rnbd transport path.

Arguments:
    <path>          In order to display path information, path name or identifier
                    has to be provided, i.e. st401b-2:1.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Sessname       Name of the session.
                    pathname        Path name      Path name
                    src_addr        Client Addr    Client address of the path
                    src_addr_s      Client Addr    Normalized client address.
                    dst_addr        Server Addr    Server address of the path
                    dst_addr_s      Server Addr    Normalized server address.
                    hca_name        HCA            HCA name
                    hca_port        Port           HCA port
                    state           State          Name of the path
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    reconnects      Reconnects     Reconnects
                    direction       Direction      Direction of the path: incoming or outgoing

                    Default: sessname,hca_name,hca_port,dst_addr_s,state,tx_bytes,rx_bytes,inflights,reconnects

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    help            Display help and exit. [fields|all]


.B

rnbd client path disconnect <path> [OPTIONS]

Disconnect a path of a given session

Arguments:
    <identifier>    Name or identifier of of a path:
                    [pathname], [sessname:port], etc.

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client path reconnect <path> [OPTIONS]

Disconnect and connect again a single path of a session

Arguments:
    <identifier>    Name or identifier of a path:
                    [pathname], [sessname:port], etc.

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client path add <session> <path> [OPTIONS]

Add a new path to an existing session

Arguments:
    <session>       Name of the session to add the new path to
    <path>          Path to be added: [src_addr@]dst_addr
                    Address is of the form ip:<ipv4>, ip:<ipv6> or gid:<gid>

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client path delete <path> [OPTIONS]

Delete a given path from the corresponding session

Arguments:
    <path>          Name or any unique identifier of a path:
                    [pathname], [sessname:port], etc.

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd client path readd <path> [OPTIONS]

Delete and add again a given path to the corresponding session

Arguments:
    <path>          Name or any unique identifier of a path:
                    [pathname], [sessname:port], etc.

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd server device list [OPTIONS]

List information on devices.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session        Name of the RTRS session of the device
                    mapping_path    Mapping Path   Mapping name of the remote device
                    devname         Device         Device name under /dev/. I.e. rnbd0
                    devpath         Device path    Device path under /dev/. I.e. /dev/rnbd0
                    access_mode     Access Mode    RW mode of the device: ro, rw or migration
                    rx_sect         RX             Amount of data read from the device
                    tx_sect         TX             Amount of data written to the device
                    direction       Direction      Direction of data transfer: imported or exported
                    Default: sessname,mapping_path,devname,access_mode

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    notree          Don't display paths for each sessions
    noheaders       Don't print headers
    nototals        Don't print totals
    help            Display help and exit. [fields|all]


.B

rnbd server device show <device> [OPTIONS]

Show information about an rnbd block device.

Arguments:
    <device>        Name of a local or a remote block device.
                    I.e. rnbd0, /dev/rnbd0, d12aef94-4110-4321-9373-3be8494a557b.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session        Name of the RTRS session of the device
                    mapping_path    Mapping Path   Mapping name of the remote device
                    devname         Device         Device name under /dev/. I.e. rnbd0
                    devpath         Device path    Device path under /dev/. I.e. /dev/rnbd0
                    access_mode     Access Mode    RW mode of the device: ro, rw or migration
                    rx_sect         RX             Amount of data read from the device
                    tx_sect         TX             Amount of data written to the device
                    direction       Direction      Direction of data transfer: imported or exported
                    Default: sessname,mapping_path,devname,access_mode

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    help            Display help and exit. [fields|all]


.B

rnbd server session list [OPTIONS]

List information on sessions.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session name   Name of the session
                    path_cnt        Path cnt       Number of paths
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    direction       Direction      Direction of the session: incoming or outgoing
                    Default: sessname,path_cnt,tx_bytes,rx_bytes,inflights

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    notree          Don't display paths for each sessions
    noheaders       Don't print headers
    nototals        Don't print totals
    help            Display help and exit. [fields|all]


.B

rnbd server session show <session> [OPTIONS]

Show information about an rnbd session.

Arguments:
    <session>       Session name or remote hostname.
                    I.e. ps401a-1@st401b-2, st401b-2, <ip1>@<ip2>, etc.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Session name   Name of the session
                    path_cnt        Path cnt       Number of paths
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    direction       Direction      Direction of the session: incoming or outgoing
                    Default: sessname,path_cnt,tx_bytes,rx_bytes,inflights

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    help            Display help and exit. [fields|all]


.B

rnbd server session disconnect <session> [OPTIONS]

Disconnect all paths on a given session

Arguments:
    <session>       Name or identifier of a session.

Options:
    verbose         Verbose output
    help            Display help and exit


.B

rnbd server path list [OPTIONS]

List information on paths.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Sessname       Name of the session.
                    pathname        Path name      Path name
                    src_addr        Client Addr    Client address of the path
                    src_addr_s      Client Addr    Normalized client address.
                    dst_addr        Server Addr    Server address of the path
                    dst_addr_s      Server Addr    Normalized server address.
                    hca_name        HCA            HCA name
                    hca_port        Port           HCA port
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    direction       Direction      Direction of the path: incoming or outgoing
                    Default: sessname,hca_name,hca_port,src_addr_s,tx_bytes,rx_bytes,inflights

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    notree          Don't display paths for each sessions
    noheaders       Don't print headers
    nototals        Don't print totals
    help            Display help and exit. [fields|all]


.B

rnbd server path show <path> [OPTIONS]

Show information about an rnbd transport path.

Arguments:
    <path>          In order to display path information, path name or identifier
                    has to be provided, i.e. st401b-2:1.

Options:
    {fields}        Comma separated list of fields to be printed. The list can be
                    prefixed with '+' or '-' to add or remove fields from the
                    default selection.

                    Field           Header         Description
                    sessname        Sessname       Name of the session.
                    pathname        Path name      Path name
                    src_addr        Client Addr    Client address of the path
                    src_addr_s      Client Addr    Normalized client address.
                    dst_addr        Server Addr    Server address of the path
                    dst_addr_s      Server Addr    Normalized server address.
                    hca_name        HCA            HCA name
                    hca_port        Port           HCA port
                    rx_bytes        RX             Bytes received
                    tx_bytes        TX             Bytes send
                    inflights       Inflights      Inflights
                    direction       Direction      Direction of the path: incoming or outgoing
                    Default: sessname,hca_name,hca_port,src_addr_s,tx_bytes,rx_bytes,inflights

    {format}        Output format: csv|json|xml
    {unit}          Units to use for size (in binary): B|K|M|G|T|P|E
    help            Display help and exit. [fields|all]


.B

rnbd server path disconnect <path> [OPTIONS]

Disconnect a path of a given session

Arguments:
    <identifier>    Name or identifier of of a path:
                    [pathname], [sessname:port], etc.

Options:
    verbose         Verbose output
    help            Display help and exit


.SH EXAMPLES
List server devices

.B rnbd server devices list

List client sessions

.B rnbd client sessions list 

List paths of server, display sizes in KB, display all columns


.B rnbd server paths list K all

List imported on client devices, show only mapping_path and devpath, output in json

.B rnbd client devices list mapping_path,devpath json

.SH COPYRIGHT
Copyright \(co 2019 - 2020 IONOS Cloud GmbH. All Rights Reserved
.SH AUTHORS
Danil Kipnis <danil.kipnis@cloud.ionos.com>
.RE
Lutz Pogrell <lutz.pogrell@cloud.ionos.com>
